ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.collections DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_item_collections DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.highlights DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reading_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_streaks DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements DISABLE ROW LEVEL SECURITY;
